# Generated by Django 5.1.6 on 2025-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd', models.CharField(max_length=20, unique=True, verbose_name='Số báo danh')),
                ('toan', models.FloatField(verbose_name='Toán')),
                ('ngu_van', models.FloatField(verbose_name='Ngữ văn')),
                ('ngoai_ngu', models.FloatField(verbose_name='Ngoại ngữ')),
                ('vat_ly', models.FloatField(verbose_name='Vật lý')),
                ('hoa_hoc', models.FloatField(verbose_name='Hóa học')),
                ('sinh_hoc', models.FloatField(verbose_name='Sinh học')),
                ('lich_su', models.FloatField(verbose_name='Lịch sử')),
                ('dia_ly', models.FloatField(verbose_name='Địa lý')),
                ('giao_duc_cong_dan', models.FloatField(verbose_name='Giáo dục công dân')),
                ('ma_ngoai_ngu', models.CharField(max_length=10, verbose_name='Mã ngoại ngữ')),
            ],
        ),
    ]
